# Generated by Django 4.2.2 on 2023-08-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0003_alter_reservation_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='flightNumber',
            new_name='flightId',
        ),
    ]
